name: Build Desktop Packages

on:
  [workflow_dispatch]

jobs:
  create-linux-package:
    runs-on: ubuntu-latest
    name: Create Deb Package
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      # Build Desktop Uber Jar application
      - name: Desktop Uber Jar
        run: ./gradlew :desktop:packageUberJarForCurrentOS

      # Build Desktop Packaged application
      - name: Desktop App Package
        run: ./gradlew :desktop:packageDeb

      # Create a Draft Release
      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: "v3.3.0"
          artifacts: "desktop/build/compose/jars/*.jar,desktop/build/compose/binaries/main/*/*"
          token: ${{ secrets.GH_TOKEN }}
          commit: main


  # Windows Package
  create-win-package:
    runs-on: windows-latest
    name: Create Windows Package
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      # Build Desktop Uber Jar application
      - name: Desktop Uber Jar
        run: ./gradlew :desktop:packageUberJarForCurrentOS

      # Build Desktop Packaged application
      - name: Desktop App Package
        run: ./gradlew :desktop:packageMsi

      # Create a Draft Release
      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: "v3.3.0"
          artifacts: "desktop/build/compose/jars/*.jar,desktop/build/compose/binaries/main/*/*"
          token: ${{ secrets.GH_TOKEN }}
          commit: main


  create-mac-package:
    runs-on: macos-latest
    name: Create Mac Package
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      # Build Desktop Uber Jar application
      - name: Desktop Uber Jar
        run: ./gradlew :desktop:packageUberJarForCurrentOS

      # Build Desktop Packaged application
      - name: Desktop App Package
        run: ./gradlew :desktop:packageDmg

      # Create a Draft Release
      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: "v3.3.0"
          artifacts: "desktop/build/compose/jars/*.jar,desktop/build/compose/binaries/main/*/*"
          token: ${{ secrets.GH_TOKEN }}
          commit: main
